google/go-dap

cmd/mockserver/server.go, cmd/mockserver/server_test.go
The server now uses the following goroutines:
- "main" goroutine accepts client connections one by one and handles them serially by reading and decoding incoming requests and dispatching each one to a new goroutine for further processing.
- per-request goroutines process each request as if letting fake debugger take over. They send events and responses via the sender goroutine.
- sender goroutine listens for messages to send and writes them to the client connection.
=> Make mock server concurrent

io.go, io_test.go
I played with fuzzing go-dap and found that Content-Length's value is
not sanity-checked and we happily accept anything. Huge values cause the
program to crash or to hang, or just panic.
Also small restructure to vars/constants in io.go
=> Harden protocol parsing against arbitrary Content-Length

cmd/gentypes/gentypes.go, schematypes.go, schematypes_test.go
All top-level DAP types implementing Message have a sequence number and a
type. Expose these as Message methods.
isMessage is removed because it's no longer necessary
=> Add GetSeq method to the Message interface

cmd/gentypes/gentypes.go, cmd/mockserver/server_test.go
Test fails since #40 removed "omitempty" from allThreadsContinued, and the
test expects hard-coded JSON strings for the responses.
=> Fix failing server test

cmd/gentypes/gentypes.go, schematypes.go
We don't actually need a `GetSeq` method on each message type. Since all messages embed `ProtocolMessage`, `GetSeq` on this type is sufficient. This is not breaking the API.
I verified this works by using the updated schematypes with delve/service/dap.
This should also simplify some of the discussion around #41 and #42
=> Only emit GetSeq for ProtocolMessage, not all message types

cmd/gentypes/debugProtocol.json, cmd/gentypes/gentypes.go, schematypes.go
This should go in after #43 to avoid churn of the generated `GetSeq` methods - after #43 the diff on schematypes.go will be much smaller.
=> Update debugProtocol.json schema to newest version: 1.41

cmd/gentypes/gentypes.go, schematypes.go
=> Interfaces for Request, Response & Event

schematypes_test.go
Updating the sanity checks in `schematypes_test.go` for the new `ResponseMessage` interface.
=> Test adherence to a new interface

cmd/gentypes/gentypes.go, codec_test.go, schematypes.go, schematypes_test.go
Replace AttachRequestArguments type with just a map, same way we have this for LaunchRequest. The arguments are implementation specific and can overlap between the requests. Create a shared interface with to access them.
=> AttachRequest.Arguments should be an arbitrary map

io.go, io_test.go
Test_readContentLengthHeader has one case that has large const.
It overflows 32bit int, then causes test failure.
io_test.go:120:61: constant 9223372036854775807 overflows int
=> Fix int overflow on 32bit

codec.go, codec_test.go
Adding this field will enable clients of this library to better
handle decoding errors.
=> Add Seq field to DecodeProtocolMessageFieldError

cmd/gentypes/gentypes.go, codec.go, codec_test.go, schematypes.go
The DAP spec includes that the default values for LinesStartAt1,
ColumnsStartAt1 and PathFormat are nonzero values (true, true, and
"path"). Set these values before decoding.
Additionally, remove the omitzero flags from LinesStartAt1 and
ColumnsStartAt1, since this will not send the value if they are
false.
=> Add default values for initialize request arguments

cmd/gentypes/gentypes.go, codec_test.go, schematypes.go, schematypes_test.go
Launch/Attach requests' arguments are supposed to be implementation
specific. By defining them as json.RawMessage, we leave decoding &
encoding of these fields up to the implementation.
Updates https://github.com/go-delve/delve/pull/2571
=> all: use json.RawMessage for launch/attach arguments

cmd/gentypes/gentypes.go, codec.go, schematypes.go
The mapping from event / response id to event and response types
can be done in generating. This makes sure that the maps stay up
to date with the spec.
=> cmd/gentypes: generate response and event ctor

cmd/gentypes/gentypes.go, schematypes.go
Currently, an empty breakpoint contains a `"source"` field with an empty object:
```go
data, _ := json.Marshal(dap.Breakpoint{})
fmt.Println(string(data))
// {"verified":false,"source":{}}
//                     ^^^^^^^^
```
This means that `BreakpointEvent` types with missing source are serialised with an empty source object, which clears the breakpoint location in the UI.
This change makes the `"source"` field optional, so that an empty breakpoint serialises as:
```go
data, _ := json.Marshal(dap.Breakpoint{})
fmt.Println(string(data))
// {"verified":false}
```
Fixes #66
=> Make `Source` field in `Breakpoint` events optional

.github/workflows/go.yml, cmd/mockserver/server_test.go, internal/test.sh
The default branch for google/go-dap is now main. Also update the go versions and the github action versions.
Fixes #76
=> .github/workflows: update workflow target branch

cmd/gentypes/gentypes.go, schematypes.go
This fixes an unintentional change from #75. Type aliases to primitives (like string) do not need to be pointers, because their zero values will be omitted during JSON serialization if omitempty is set.
As this is a bug fix for a released version, I have opted to not restructure the code much to minimize duplicate deserializations.
Fixes #80
=> Fix type aliases being emitted as pointers.

codec.go, codec_test.go
Right now, go-dap supports vanilla DAP types, but it falls short when used for custom request types. This PR adds the `Codec` type with which users can register new DAP messages. After registering the new type, `Codec` can also deserialize the custom DAP message.
Custom DAP messages still need to implement the dap.Message interface.
Fixes #69
=> Add a new `Codec` type that allows to register custom DAP commands

codec.go
So far, the message was parsed three times:
1) To determine if it is a request/response/event (->Type) 2) To determine the command (->Command/Event/Success) to determine the
right ctor
3) A final pass with the right ctor
Steps 1+2 can be combined into a single step by using a union type of the fields that are required to determine the right ctor. This PR does exactly that. It combines steps 1+2 so that the message needs to be parsed only once to determine the ctor.
The final parsing step (3) with the right ctor can of course not be elided. So the number of parsing operations is reduced from 3 to 2. This is a big win, because JSON parsing is slow, especially for large messages.
=> Optimize message parsing

codec.go
When an error occurs, there is currently no good way to access the bad message, because the bytes have been consumed from the input stream and the error does not include the raw message. This makes it hard to debug and makes logs less useful, because just the message type/command is often not enough.
This PR adds the raw bytes to DecodeProtocolMessageFieldError to make this easier.
=> Include the raw message in the error

cmd/gentypes/gentypes.go, schematypes.go
This makes it easier to implement the
ResponseMessage/RequestMessage/EventMessage interface, because you only need to embed Response/Request/Message, respectively.
=> Move interface method to embedded type

cmd/gentypes/gentypes.go, schematypes.go
The restart request contains the last launch or attach arguments and should also be treated as an opaque embedded JSON message.
=> Treat RestartRequest arguments identical to Launch/Attach arguments

cmd/gentypes/gentypes.go, codec_test.go, schematypes.go
So far, these fields were represented as `interface{}`, which means that the JSON library parsed these fields. However, they contain opaque data, which makes it very inconvenient to work with such a message. Now, fields with a submessage are represented as json.RawMessage, so that applications can re-parse these submessages into the correct structure more easily.
If the list of types only contains fundamental types, we stick with `interface{}`.
=> Use json.RawMessage when polymorphic fields contain submessages

cmd/gentypes/gentypes.go, go.mod, schematypes.go
This alias was added in go 1.18, which has been out for a while already.
As `strings.Title()` is deprecated this PR also implements `goFieldName()` with a hand-rolled implementation which handles unicode correctly.
=> Use the `any` alias for `interface{}`
